#!/usr/bin/env python
import graviton
import sys

def printControl(control):
  print "control:", control.name
  for method in control.methods:
    print "\tmethod:", method.name
  for property in control.properties:
    print "\tproperty:", property.name, "=", property.value
  for subcontrol in control.controls:
    printControl(subcontrol)

if len(sys.argv) == 1:
  b = graviton.Browser()
  b.discover()
  for node in b.results:
    print "Looking at node", node.url()
    for control in node.controls():
      printControl(control)
else:
  node = graviton.Node(sys.argv[1], int(sys.argv[2]))
  print "Looking at node", node.url()
  for control in node.controls():
    printControl(control)
