#ifndef CONFIG_H
#define CONFIG_H

#define GRAVITON_VERSION_MAJOR @GRAVITON_VERSION_MAJOR@
#define GRAVITON_VERSION_MINOR @GRAVITON_VERSION_MINOR@
#define GRAVITON_VERSION_PATCH @GRAVITON_VERSION_PATCH@
#define GRAVITON_VERSION "@GRAVITON_VERSION_MAJOR@.@GRAVITON_VERSION_MINOR@.@GRAVITON_VERSION_PATCH@" 
#define GRAVITON_DEFAULT_DISCOVERY_PLUGIN_PATH "@GRAVITON_DISCOVERY_PLUGIN_PATH@"
#define GRAVITON_DEFAULT_PUBLISH_PLUGIN_PATH "@GRAVITON_PUBLISH_PLUGIN_PATH@"

// Configured in graviton/client/CMakeLists.txt
#cmakedefine GRAVITON_ENABLE_STREAMS

#endif // CONFIG_H
