#ifndef CONFIG_H
#define CONFIG_H

#define GRAVITON_VERSION_MAJOR @GRAVITON_VERSION_MAJOR@
#define GRAVITON_VERSION_MINOR @GRAVITON_VERSION_MINOR@
#define GRAVITON_VERSION_PATCH @GRAVITON_VERSION_PATCH@
#define GRAVITON_VERSION "@GRAVITON_VERSION_MAJOR@.@GRAVITON_VERSION_MINOR@.@GRAVITON_VERSION_PATCH@" 

#endif // CONFIG_H
