#ifndef __GRAVITON_CLOUD_H__
#define __GRAVITON_CLOUD_H__

#include <glib.h>
#include <glib-object.h>
#include <graviton/node.h>
#include <graviton/discovery-method.h>

G_BEGIN_DECLS

#define GRAVITON_CLOUD_TYPE            (graviton_cloud_get_type ())
#define GRAVITON_CLOUD(obj)            (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRAVITON_CLOUD_TYPE, GravitonCloud))
#define GRAVITON_CLOUD_CLASS(klass)    (G_TYPE_CHECK_CLASS_CAST ((klass), GRAVITON_CLOUD_TYPE, GravitonCloudClass))
#define IS_GRAVITON_CLOUD(obj)         (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRAVITON_CLOUD_TYPE))
#define IS_GRAVITON_CLOUD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRAVITON_CLOUD_TYPE))
#define GRAVITON_CLOUD_GET_CLASS(obj)  (G_TYPE_INSTANCE_GET_CLASS ((obj), GRAVITON_CLOUD_TYPE, GravitonCloudClass))

//TODO: Rename to GravitonCloud
typedef struct _GravitonCloud      GravitonCloud;
typedef struct _GravitonCloudClass GravitonCloudClass;
typedef struct _GravitonCloudPrivate GravitonCloudPrivate;

struct _GravitonCloudClass
{
  GObjectClass parent_class;
};

/**
 * GravitonCloud: An interface to a given Graviton cloud
 * 
 * A GravitonCloud provides a unified view of a Graviton cloud, which is a
 * collection of #GravitonNode.
 *
 * Cloud membership is determined by comparing the locally stored public key
 * with a challenge generated by a remote #GravitonNode's private key.
 *
 * Clouds can provide a number of different ways to enumerate their members:
 *
 * * The graviton.cloud graviton service
 * * Configuration of 
 *
 */
struct _GravitonCloud
{
  GObject parent;

  /*< private >*/
  GravitonCloudPrivate *priv;
};

GType graviton_cloud_get_type (void);

GravitonCloud *graviton_cloud_new (const gchar *cloud_id);
GravitonCloud *graviton_cloud_new_default_cloud ();

GList *graviton_cloud_get_found_nodes (GravitonCloud *client);

void graviton_cloud_add_discovery_method (GravitonCloud *client, GravitonDiscoveryMethod *method);

void graviton_cloud_load_discovery_plugins (GravitonCloud *client);

GArray *graviton_cloud_find_discovery_plugins (GravitonCloud *client);

GravitonNode *graviton_cloud_find_node_sync (GravitonCloud *client, const gchar *guid, GError **error);
GList *graviton_cloud_find_service_sync (GravitonCloud *client, const gchar *serviceName, GError **error);

const gchar *graviton_cloud_get_cloud_id (GravitonCloud *client);
const gchar *graviton_cloud_get_cloud_name (GravitonCloud *client);

G_END_DECLS

#endif
